/*
 * Generated by the Mule project wizard. http://mule.mulesoft.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.testcase;

import org.mule.api.MuleMessage;
import org.mule.api.client.MuleClient;
import org.mule.tck.junit4.FunctionalTestCase;
import org.mule.transport.NullPayload;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

public class TestCaseTestCase extends FunctionalTestCase
{
    protected String getConfigResources()
    {
        //TODO You'll need to edit this file to make the test applicable to your module
        return "testcase-functional-test-config.xml";
    }

//    @Test
    public void testcase() throws Exception
    {
//        Thread.sleep(600000);
        MuleClient client = muleContext.getClient();
//        client.dispatch("vm://in", "some data", null);

//        MuleMessage result = client.request("vm://out", RECEIVE_TIMEOUT);
        MuleMessage result = client.send("http://localhost:9999/test", "test", null);
        assertNotNull(result);
        assertNull(result.getExceptionPayload());
        assertFalse(result.getPayload() instanceof NullPayload);

    }
}
